server:
  error:
    include-message: always

spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

app:
  env:
    binance-rest-url: ${env.BINANCE_REST_URL}
    binance-wss-url: ${env.BINANCE_WSS_URL}
    binance-api-key: ${env.BINANCE_API_KEY}
    binance-api-secret: ${env.BINANCE_API_SECRET}
    tradeables: ${env.TRADEABLES:XRP}
    bridge: ${env.BRIDGE:USDT}
    bridgeAmount: ${env.BRIDGE_AMOUNT:10}
  data:
    mongodb:
      database: eltrader
      uri: mongodb://localhost:27017/?replicaSet=rs0

mongock:
  change-logs-scan-package: com.leantrace.mongo.changelogs
  transaction-enabled: false
